In [55]:
import numpy as np

##calculo nomra infinito  norma_inf = np.linalg.norm(A, ord = np.inf)

def metodo_jacobi(A, b, x0, n_max = 15, eps = 10**(-5)):
    
    it = 1
    n = len(A)
    x = np.zeros(n)
    error = 1
    while (it <= n_max and error > eps):
        for i in range(n):
            suma = 0
            for j in range(n):
                if i != j:
                    suma += A[i,j]*x0[j]
                    
            x[i] = (b[i] - suma)/A[i,i]
            
        print(x)
        error = np.linalg.norm(x-x0, ord = np.inf)
        x0[:] = x
        it += 1

    if it > n_max :
        print("Numero maximo de iteraciones alcanzado")
        return x

    print(f"Convergencia alcanzada en la iteracion {it-1}")
    return x    
            
            
A = np.array([[6,-2,1],[-2,7,2],[1,2,-5]])
B = np.array([4,1,-4.5])
n = len(A)
x0 = np.zeros(n)
x = metodo_jacobi(A,B,x0,10, 10**(-2))
print(x)

    
    

[0.66666667 0.14285714 0.9       ]
[0.56428571 0.07619048 1.09047619]
[ 0.51031746 -0.00748299  1.04333333]
[ 0.49028345 -0.00943311  0.99907029]
[ 0.49701058 -0.00251053  0.99428345]
Convergencia alcanzada en la iteracion 5
[ 0.49701058 -0.00251053  0.99428345]


In [54]:
"""
00 01 02
10 11 12
20 21 22
"""
import numpy as np

def metodo_seidel(A,b,x0, n_max = 10, eps = 10**(-2)):
    n = len(A)
    it = 1
    error = 1
    x_ant = x0.copy()
    while( it <= n_max and error > eps):
        for i in range(n):
            suma = 0
            for j in range(n):
                if i != j :
                    suma += A[i,j]*x0[j]
                    
            x0[i] = (b[i] - suma)/A[i,i]

        print(f"x_ant :{x_ant}")
        print(f"x : {x0}")
        print()
      
        error = np.linalg.norm(x0 - x_ant , ord = np.inf)
        x_ant[:] = x0
        it += 1
        

    if it > n_max :
        print("Numero maximo de iteraciones alcanzado")
    else:
        print(f"Convergencia alcanzada en la iteracion {it-1}")
        
    return x0
        
            
A = np.array([[6,-2,1.0],[-2,7,2.0],[1,2,-5.0]])
B = np.array([4,1,-4.5])
n = len(A)
x0 = np.zeros(n)
x = metodo_seidel(A,B,x0,10,10**(-2))
print(x)           
        
        

x_ant :[0. 0. 0.]
x : [0.66666667 0.33333333 1.16666667]

x_ant :[0.66666667 0.33333333 1.16666667]
x : [ 0.58333333 -0.02380952  1.00714286]

x_ant :[ 0.58333333 -0.02380952  1.00714286]
x : [ 0.49087302 -0.00464853  0.99631519]

x_ant :[ 0.49087302 -0.00464853  0.99631519]
x : [4.99064626e-01 7.85552316e-04 1.00012715e+00]

Convergencia alcanzada en la iteracion 4
[4.99064626e-01 7.85552316e-04 1.00012715e+00]


In [9]:
import numpy as np
def metodo_sor(A, b, x0, w, n_max = 10,eps = 10**(-3)):
    n = len(A)
    x_ant = x0.copy()
    it = 1
    error = 1
    
    while( it <= n_max and error > eps):
        for i in range(n):
            suma = 0
            for j in range(n):
                if i != j:
                    suma += A[i,j]*x0[j]

            x0[i] = w*((b[i] - suma)/A[i,i]) + (1-w)*x_ant[i]

        error = np.linalg.norm(x0 - x_ant, ord = np.inf)
        x_ant[:] = x0
        it += 1

    if(it > n_max):
        print("Numero maximo de iteraciones alcanzadas")
    else:
        print(f"Convergencia alcanzada en la iteracion {it-1}")

    return x0
        
            
    
A = np.array([[6,-2,1.0],[-2,7,2.0],[1,2,-5.0]])
B = np.array([4,1,-4.5])
n = len(A)
x0 = np.zeros(n)
w = 1.2
x = metodo_sor(A,B,x0,w,15,10**(-2))
print(x)  



















Convergencia alcanzada en la iteracion 7
[ 4.98331784e-01 -2.37922829e-04  9.99522816e-01]
