In [4]:
import numpy as np
def sustitucion_atras(A, b):
    n = len(A)
    x = np.zeros(n)

    x[n-1] = b[n-1] / A[n-1,n-1]

    for i in range(n-2, -1, -1):
        suma = 0
        for j in range(i+1, n):
            suma += A[i,j]*x[j]
            
        x[i] = (b[i] - suma)/A[i,i]

    return x




In [5]:
def sustitucion_adelante(A,b):
    
    n = len(A)
    x = np.zeros(n)
    
    x[0] = b[0]/A[0,0]

    for i in range(1,n):
        suma = 0
        for j in range(i):
            suma += A[i,j]*x[j]
        x[i] = (b[i] - suma)/A[i,i]

    return x

A = np.array([[6,0,0.0],[8,4,0.0],[2,1,2.0]])
b = np.array([6,12,5.0])
x = sustitucion_adelante(A, b)

print(x)

    

[1. 1. 1.]


In [8]:
def factorizacion_lu(A):
    n = len(A)
    for k in range(n-1):
        for i in range(k+1,n):
            A[i,k] = A[i,k]/A[k,k]
            for j in range(k+1,n):
                A[i,j] = A[i,j] - (A[i,k]*A[k,j])


A = np.array([[1,3,2.0],
              [1,5,0.0],
              [2,4,1.0]
             ])

print(f"Antes de LU :\n{A}")
factorizacion_lu(A)

print(f"Despues de LU:\n{A}")




        

Antes de LU :
[[1. 3. 2.]
 [1. 5. 0.]
 [2. 4. 1.]]
Despues de LU:
[[ 1.  3.  2.]
 [ 1.  2. -2.]
 [ 2. -1. -5.]]


In [35]:
def factorizacion_lu2(A,n):
    """
        Esta funcion recibe como parametro la matriz A (que debe ser cuadrada) y el orden de la matriz.
        Esta funcion, aplica la factorizacion LU y guarda esa factorizacion
        en la misma matriz A.
        Una vez ejecutada la funcion, en memoria queda A factorizada de la forma LU
    """
    for k in range(n-1):
        for i in range(k+1,n):
            #Calculo los multiplicadores
            A[i,k] = A[i,k]/A[k,k] 
            for j in range(k+1,n):
                #Recalculo la fila despues de haber calculado el multiplicador
                A[i,j] = A[i,j] - A[i,k]*A[k,j] 

"""
a00 a01 a02
0   a11 a12
0   0   a22
"""
def sustitucion_atras(A,b,n):
    x = np.zeros(n)
    #3
    x[n-1] = b[n-1]/A[n-1,n-1]  #x[2]
    for i in range(n-2,-1,-1): #n:1
        suma = 0
        for j in range(i+1,n):
            suma += A[i,j]*x[j]
            
        x[i] = (b[i] - suma)/A[i,i]
    return x

def sustitucion_adelante(A,b,n):
    x = np.zeros(n)
    
    x[0] = b[0]

    for i in range(1,n):
        suma = 0
        for j in range(i):
            suma += A[i,j]*x[j]
        x[i] = (b[i] - suma)
        
    return x

def triangulizacion(A,b):
    """
        Control para asegurar que la matriz sea cuadrada de orden n y b sea del orden nx1
    """
    filas, colum = A.shape
    if filas != colum :
        raise ValueError("La matriz de coeficientes debe ser cuadrada nxn")
    if filas != len(b) :
        raise ValueError("El termino independiente debe ser del orden nx1")

    """
    Dado el sistema AX = b
    Aplicamos a la matriz A, factorizacion LU
    """
    factorizacion_lu2(A,filas)
    print(A)
    """
    Una vez que tenemos A = LU
    L : matriz triangular inferior (mti)
    U : matriz triangular superior (mts)
    Aplicamos la siguiente sustitucion
    LUx = b
    Ux = y
    Ly = b
    Primero resolvemos Ly = b, con sustitucion hacia atras, pues L es mti
    """
    y =  sustitucion_adelante(A,b,filas)
    print(y)
    """
    Una vez que tenemos y,
    podemos calcular Ux = y, aplicando susitucion hacia adelante, pues U es mts
    """
    x = sustitucion_atras(A,y,filas)
    return x

A = np.array([[1,3,2.0],
              [1,5,0.0],
              [2,4,1.0]])

b = np.array([9,11,11.0])

x0 = triangulizacion(A,b)
print(x0)


    

[[ 1.  3.  2.]
 [ 1.  2. -2.]
 [ 2. -1. -5.]]
[ 9.  2. -5.]
[1. 2. 1.]


In [43]:
"""
a00 a01 a02
a10 a11 a12
a20 a21 a22
"""

import numpy as np
def factorizacionLU_pivot(A):
    filas, colum = A.shape
    if(filas != colum):
        raise ValueError("La matriz debe ser de orden n x n")

    n = filas
    #Genero vector  pivot ordenado desde 0 a n-1
    piv = list(range(n))
    
    for k in range(n-1):
        #Busco el pivot
        p = k #indece del pivot en la columna k
        max_val = abs(A[k,k]) #A00
        for i in range(k+1, n):
            if abs(A[i,k]) > max_val:
                max_val = abs(A[i,k])
                p = i

        #cambio el indice del pivot -> intercambio columnas
        if p != k :
            A[k], A[p] = A[p].copy(), A[k].copy()
            piv[k], piv[p] = piv[p], piv[k]

        #una vez intercambiada las filas aplico LU
        #Modifico la misma matriz A
        for i in range(k+1,n):
            A[i,k] = A[i,k]/A[k,k]
            for j in range(k+1, n):
                A[i,j] = A[i,j] - (A[i,k]*A[k,j])

    return piv
                
A = np.array([[0,3,2.0],
              [-4,-2,1.0],
              [1,4,-2.0]])

pivote = factorizacionLU_pivot(A)

print(A)
print()
print(pivote)

        

[[-4.         -2.          1.        ]
 [-0.25        3.5        -1.75      ]
 [-0.          0.85714286  3.5       ]]

[1, 2, 0]


In [51]:
def factorizacionLU_pivot_escalado(A):
    """
    Esta funcion recibe como parametro la matriz A de orden nxn.
    Aplica factorizacion LU con pivoteo parcial escalado 
    y guarda la factorizacion sobre la misma matriz A.
    Retorna el vector Pivote, con las permutaciones que se hicieron en A.
    """
    filas, colum = A.shape
    if filas != colum :
        raise ValueError("La matriz debe ser del orden n x n")

    n = filas
    
    #Obtengo el vector de scala -> maximo de cada fila
    scale = np.zeros(n)
    for i in range(n):
        max_val = 0
        for j in range(n):
            if abs(A[i,j]) > max_val:
                max_val = abs(A[i,j])
        scale[i] = max_val

    #genero el vector de pivot -> vector ordenado de 0 a n-1
    pivote = list(range(n))

    for k in range(n-1):
        p = k #indice del pivot, inicialmente 0
        
        max_ratio = abs(A[k,k])/scale[k] if scale[k] != 0 else 0

        #hago el escalamiento implicito
        for i in range(k+1,n):
            ratio = abs(A[i,k])/scale[i] if scale[k] != 0 else 0
            if ratio > max_ratio:
                max_ratio = ratio
                p = i #nuevo indice del pivot -> intercambio de fila

        #verifico que deba hacer un intercambio de filas
        if p != k :
            A[k], A[p] = A[p].copy(), A[k].copy() 
            pivote[k], pivote[p] = pivote[p], pivote[k]
            scale[k], scale[p] = scale[p], scale[k]

        #aplico factorizacion LU:
        for i in range(k+1,n):
            A[i,k] = A[i,k]/A[k,k]
            for j in range(k+1,n):
                A[i,j] = A[i,j] - (A[i,k]*A[k,j])

    return pivote
            
            
A = np.array([[4, 2, 1.0],
              [-1, 0, 6.0],
              [2, 2, 1.0]
             ])

pivote = factorizacionLU_pivot_escalado(A)

print(A)
print()
print(pivote)
                
        

[[ 4.    2.    1.  ]
 [ 0.5   1.    0.5 ]
 [-0.25  0.5   6.  ]]

[0, 2, 1]
